server:
  port: 8070
spring:
#   sql:
#    init:
#      mode: always
   datasource:
      url: jdbc:mysql://localhost:3306/tp_jobs
#      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Temp1234
   Jpa:
      hibernate.ddl-auto: update
   Security:
      user:
         name: User
         password: Temp1234
   mvc:
     pathmatch:
       matching-strategy: ant-path-matcher
   application:
    name: jobseeker-service
#   zipkin:
#     base-url: http://localhost:9411
eureka:
   instance:
      prefer-ip-address: true
      hostname: localhost   
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      jobseeker-service-Token:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 5
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s