server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  zipkin:
      base-url: http://localhost:9411    
  
  cloud:
     gateway:
      routes:
      - id: user-talentportal
        uri: lb://user-talentportal
        predicates:
          - Path=/talentportal/**
      - id: jobseeker-service
        uri: lb://jobseeker-service
        predicates:
          - Path=/jobseeker/**   
      - id: Employer-service
        uri: lb://Employer-service
        predicates:
          - Path=/employer/** 
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        
        

  

eureka: 
   instance:
      prefer-ip-address: true 
      hostname: localhost  
 